usdot-fhwa-stol/novatel_gps_driver

novatel_gps_driver/src/nodelets/novatel_gps_nodelet.cpp

Updates driver type to support carma 3 driver types defined in CARMAMsgs PR 13

Update driver type for carma3

---

.travis.yml
README.md
novatel_gps_driver/CHANGELOG.rst
novatel_gps_driver/CMakeLists.txt
novatel_gps_driver/include/novatel_gps_driver/novatel_gps.h
novatel_gps_driver/include/novatel_gps_driver/parsers/clocksteering.h
novatel_gps_driver/package.xml
novatel_gps_driver/src/nodelets/novatel_gps_nodelet.cpp
novatel_gps_driver/src/novatel_gps.cpp
novatel_gps_driver/src/parsers/clocksteering.cpp
novatel_gps_msgs/CHANGELOG.rst
novatel_gps_msgs/CMakeLists.txt
novatel_gps_msgs/msg/ClockSteering.msg
novatel_gps_msgs/package.xml

There have been multiple changes to the swri repo since our fork. None appear to be breaking and they add a new message type. This PR will bring our develop branch up to date with the swri master branch.

Merge swri master into our develop

---

novatel_gps_driver/CMakeLists.txt
novatel_gps_driver/include/novatel_gps_driver/novatel_gps.h
novatel_gps_driver/include/novatel_gps_driver/parsers/bestxyz.h
novatel_gps_driver/src/nodelets/novatel_gps_nodelet.cpp
novatel_gps_driver/src/novatel_gps.cpp
novatel_gps_driver/src/parsers/bestxyz.cpp
novatel_gps_driver/test/parser_tests.cpp
novatel_gps_msgs/CMakeLists.txt
novatel_gps_msgs/msg/NovatelXYZ.msg

Update our develop branch to include the addition of BESTXYZ pushed to the swri master. 
* Add ros message and parsers for BESTXYZ message

Add support for BESTXYZ topic (#42)

---

.travis.yml
README.md
novatel_gps_driver/CHANGELOG.rst
novatel_gps_driver/CMakeLists.txt
novatel_gps_driver/include/novatel_gps_driver/novatel_gps.h
novatel_gps_driver/include/novatel_gps_driver/parsers/bestxyz.h
novatel_gps_driver/include/novatel_gps_driver/parsers/clocksteering.h
novatel_gps_driver/include/novatel_gps_driver/parsers/heading2.h
novatel_gps_driver/package.xml
novatel_gps_driver/src/nodelets/novatel_gps_nodelet.cpp
novatel_gps_driver/src/novatel_gps.cpp
novatel_gps_driver/src/parsers/bestxyz.cpp
novatel_gps_driver/src/parsers/clocksteering.cpp
novatel_gps_driver/src/parsers/heading2.cpp
novatel_gps_driver/test/parser_tests.cpp
novatel_gps_msgs/CHANGELOG.rst
novatel_gps_msgs/CMakeLists.txt
novatel_gps_msgs/msg/ClockSteering.msg
novatel_gps_msgs/msg/NovatelHeading2.msg
novatel_gps_msgs/msg/NovatelXYZ.msg
novatel_gps_msgs/package.xml

This PR merges the Swri master into our master. Then we can merge our master into our develop to keep everything in sync.

Merge Swri master into carma master

---

README.md
novatel_gps_driver/CMakeLists.txt
novatel_gps_driver/include/novatel_gps_driver/novatel_gps.h
novatel_gps_driver/include/novatel_gps_driver/parsers/dual_antenna_heading.h
novatel_gps_driver/src/nodelets/novatel_gps_nodelet.cpp
novatel_gps_driver/src/novatel_gps.cpp
novatel_gps_driver/src/parsers/dual_antenna_heading.cpp
novatel_gps_driver/test/parser_tests.cpp
novatel_gps_msgs/CMakeLists.txt
novatel_gps_msgs/msg/NovatelDualAntennaHeading.msg

Sync develop with swri master
* Add DUALANTENNAHEADING message
* Add unit tests
* Update documentation for BESTXYZ, HEADING2, and DUALANTENNAHEADING messages

Feature/add dual antenna heading msg (#46)

---

novatel_gps_driver/launch/novatel_gps_driver_eth.launch

Update the driver launch file to publish heading messages by default.

Publish heading messages when launching driver

---

Dockerfile
docker/install.sh
novatel_gps_driver/CMakeLists.txt
novatel_gps_driver/config/parameters.yaml
novatel_gps_driver/launch/novatel_gps_driver_eth.launch

Update driver to conform to parameter standards

Update to match parameter standards

---

novatel_gps_driver/src/parsers/parsing_utils.cpp
novatel_gps_driver/test/parser_tests.cpp

Resync repo with swri master
SWRI PR: (#48)

Sync with Swri master

---

README.md

This change should not be merged into the master repo.

Applied standard header to the repo's readme.

---

.circleci/config.yml
Dockerfile

Update base image version to match new component release

Update base docker image version to carma-base:3.3.0

---

.circleci/config.yml
.sonarqube/sonar-scanner.properties
docker/checkout.sh
docs/pull_request_template.md

Adding updated Msgs version, pr template, and copyright updates for release 1.3.0

Release/carma novatel gps driver 1.3.0

---

.circleci/config.yml
docker/build-image.sh
docker/checkout.sh
hooks/pre_build

PR to add -d|--develop option to build-image.sh, allowing devs to more easily make images for our integration testing Docker repo

added develop option

---

docker/build-image.sh

Changes in this PR will tag images built with ./build-image.sh with the correct dockerhub repo name.
[787](https://github.com/usdot-fhwa-stol/carma-platform/issues/787)
Solves an issue created by the github repo name change, where locally built docker images would use the new github repo name as the image tag, rather than the correct dockerhub repo.
By running build-image.sh and verifying the image tag.

updated to use docker repo name

---

.circleci/config.yml
Dockerfile
docker/checkout.bash
hooks/build
hooks/pre_build

This PR is to merge the changes from release 3.4.3 back into the develop branch. Also points base images back at develop
This is needed to keep the develop branch as a working version of our released master branch.
Has been tested as part of the Wanderer testing process.

Feature/sync 3.4.3

---

docker/build-image.sh

Fixes build-image.sh to support dev images
Should have been included in
https://github.com/usdot-fhwa-stol/novatel_gps_driver/pull/62

Fix build-image.sh for dev

---

.circleci/config.yml
.sonarqube/sonar-scanner.properties
Dockerfile
docker/build-image.sh
docker/checkout.bash
docker/get-component-version.sh
docker/get-image-name.sh
docker/get-repo-name.sh
docker/get-system-version.sh
docker/install.sh
docker/system_release.sh
novatel_gps_driver/include/novatel_gps_driver/wrapper/gps_driver_wrapper.h
novatel_gps_driver/include/novatel_gps_driver/wrapper/novatel_gps_nodelet_wrapper_worker.h
novatel_gps_driver/include/novatel_gps_driver/wrapper/worker_config.h
novatel_gps_driver/launch/novatel_gps_driver_eth.launch
novatel_gps_driver/src/nodelets/wrapper/novatel_gps_nodelet_wrapper.cpp
novatel_gps_driver/src/nodelets/wrapper/novatel_gps_nodelet_wrapper_worker.cpp
novatel_gps_driver/test/wrapper/gps_nodelet_wrapper_worker_test.cpp

Updated all of the copyright dates in the repository.
Keeps the copyright up to date for legal reasons I suppose
Checked the changes and it only affect comments.
- [Y] I have added any new packages to the sonar-scanner.properties file
- [N] My change requires a change to the documentation.
- [Y] I have updated the documentation accordingly.
- [Y] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [Y] I have added tests to cover my changes.
- [Y] All new and existing tests passed.

updated copyright text

---

.circleci/config.yml
Dockerfile
docker/checkout.bash

Follow up to https://github.com/usdot-fhwa-stol/novatel_gps_driver/pull/66 to update version numbers after master sync

Update version numbers after master sync

---

.circleci/config.yml
Dockerfile
docker/checkout.bash

This PR is to merge release cabin changes into develop

Sync dev with 4.2

---

README.md

This PR is to add the dockerhub build status checks to readme

added docker hub build checks to readme

---

.circleci/config.yml
Dockerfile
README.md
docker/checkout.bash

This PR is to merge release branch isetta to master for release 4.3.0

merge Release/isetta

---

.circleci/config.yml
Dockerfile
docker/checkout.bash

Merge master branch into develop
